name = "share"
main = "src/index.ts"
compatibility_date = "2026-03-19"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"

[[kv_namespaces]]
binding = "KV"
id = "9f5e5e1925634e35965aa8527faa62bd"

[[routes]]
pattern = "icecube.to"
custom_domain = true

[[routes]]
pattern = "xn--3u9h.to"
custom_domain = true

[vars]
SITE_NAME = "icecube.to"
